name: test cloud function deploy
on: push

jobs:
  cloudfunctiondeploy:
    runs-on: ubuntu-latest
    name: Test cloud function deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
         files: 'cloudfunctions/**'
         dir_names: "true"
      - name: get list of folders modified till depth 2
        id: changed-paths
        run: |   
          ls -l
          declare -A processed_paths
          IFS=' ' read -ra files <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          for file in "${files[@]}"; do
            IFS='/' read -ra ADDR <<< "$file"
            if [ "${#ADDR[@]}" -gt 1 ]; then
              path_depth_2="${ADDR[0]}/${ADDR[1]}"
              processed_paths["$path_depth_2"]=1
            fi
          done

          for path in "${!processed_paths[@]}"; do
            echo "${path}"
          done

          # Convert associative array keys to an indexed array to remove dups
          processed_array=("${!processed_paths[@]}")

          config_dir="cloudfunctions/config"

          for path in ${processed_array[@]}; do

          function_name=$(basename "$path")
          output_array=()
          config_file="${config_dir}/${function_name}.yaml"

              if [[ -f "$config_file" ]]; then

                  yq eval-all 'select(fileIndex == 1) * select(fileIndex == 0)' "$config_file" "./environments/cloudfunctions/$BRANCH_NAME.yaml" > ${function_name}_merged.yaml
                  
                  else

                    echo "Configuration file $config_file does not exist."
                    
                    cat "./environments/cloudfunctions/$BRANCH_NAME.yaml" > ${function_name}_merged.yaml
              fi
              output_array+=(${function_name}_merged.yaml)
          done
          ls
          for output in ${output_array[@]}; do
            echo ${output}
            cat $output
          done
          


